import type { Artifact } from "@/types/domain";

/** 证据宝库 — 14 件神器种子数据（M0–M13）。 */

export const ARTIFACTS: Artifact[] = [
  {
    id: "art_m0",
    name: "奠基石：边界实验室脚手架",
    nameEn: "Foundation Stone: Boundary Lab Scaffold",
    rarity: "common",
    sourceQuestId: "m0",
    proves: "你能把一个模糊的野心装进清晰的工程结构，并以研究的姿态立项。",
    careerValue: "面试中谈到副项目时，一个结构严谨的仓库开场，比任何炫技 demo 更能建立可信度。",
    skillsProven: ["项目立项", "仓库结构设计", "研究性思维"],
    linkedinSuggestion: "发布一条短帖：宣布 Unity Native Boundary Lab 立项，附 thesis 一段话与仓库结构截图。",
    blogSuggestion: "写一篇《为什么我把 native interop 当作研究而不是 demo》的短文，阐述项目 thesis。",
    portfolioSuggestion: "在作品集中为本项目建卡片：一句 thesis + 仓库结构图。",
    resumeBullet: "发起 Unity Native Boundary Lab 研究项目，系统研究 Unity managed/native 边界的设计与成本。",
    interviewExplanation: "我把项目定位为边界研究，不是随手的 native DLL demo。",
    icon: "stone",
  },
  {
    id: "art_m1",
    name: "原生版本之石",
    nameEn: "Native Version Stone",
    rarity: "common",
    sourceQuestId: "m1",
    proves: "你能在 Unity 之外用 CMake 构建 native 库，并对二进制产物进行推理。",
    careerValue: "证明你拥有独立的 native 工具链能力，而不是依赖引擎打包的黑盒。",
    skillsProven: ["CMake", "native binary", "symbol export", "C ABI"],
    linkedinSuggestion: "分享第一次在 Unity 之外构建 native 库的体会：Debug/Release 的差异与符号导出的坑。",
    blogSuggestion: "写《从零构建一个可被 Unity 加载的 native 库》：CMake 配置、导出宏、冒烟测试。",
    portfolioSuggestion: "附上 CMake 配置片段与构建产物说明，展示跨平台构建意识。",
    resumeBullet: "使用 CMake 构建跨平台 C++ 共享库，设计稳定的 C ABI 导出层（版本查询 API）。",
    interviewExplanation: "我可以在 Unity 之外构建 native 库，并对二进制产物进行推理。",
    icon: "stone2",
  },
  {
    id: "art_m2",
    name: "初次信号：Unity 听见了 Native",
    nameEn: "First Signal: Unity Heard Native",
    rarity: "uncommon",
    sourceQuestId: "m2",
    proves: "你理解 managed 代码如何发现并调用 unmanaged 函数的完整链路。",
    careerValue: "P/Invoke 的第一性理解是所有 Unity native 集成岗位的敲门砖。",
    skillsProven: ["P/Invoke", "DllImport", "native plugin loading", "C ABI"],
    linkedinSuggestion: "发一条帖：Unity 第一次打印出 native 版本号的截图 + extern \"C\" 为什么重要的三句解释。",
    blogSuggestion: "写《EntryPointNotFoundException 完全排查指南》，用你自己的失败记录做案例。",
    portfolioSuggestion: "在项目卡片中加入调用链示意图：C# DllImport → 动态库 → C ABI 符号。",
    resumeBullet: "实现 Unity C# 到 C++ 原生库的 P/Invoke 集成，处理符号导出、插件加载与架构匹配问题。",
    interviewExplanation: "我理解 managed Unity 代码如何发现并调用 unmanaged 函数。",
    icon: "signal",
  },
  {
    id: "art_m3",
    name: "不透明句柄契约",
    nameEn: "Opaque Handle Contract",
    rarity: "rare",
    sourceQuestId: "m3",
    proves: "你能用 opaque handle 与显式生命周期设计跨 ABI 的资源所有权。",
    careerValue: "生命周期与所有权设计是系统级面试的核心考点，这件神器是你的实证。",
    skillsProven: ["RAII", "IDisposable", "opaque handle", "lifetime ownership"],
    linkedinSuggestion: "分享你的所有权表设计：谁创建、谁持有、谁销毁、谁不许触碰。",
    blogSuggestion: "写《为什么 C++ 对象不应该跨越 ABI》：从 opaque handle 到 IDisposable 的完整契约。",
    portfolioSuggestion: "展示 NativeBoundaryContext 的设计图与双重 Dispose 测试记录。",
    resumeBullet: "设计基于 opaque handle 的跨 ABI 资源管理方案，C# IDisposable 封装保证生命周期安全与幂等释放。",
    interviewExplanation: "我使用 opaque handle 与显式生命周期，而不是让 C++ 对象跨 ABI 泄漏。",
    icon: "handle",
  },
  {
    id: "art_m4",
    name: "Blittable Agent 契约",
    nameEn: "Blittable Agent Contract",
    rarity: "rare",
    sourceQuestId: "m4",
    proves: "你能设计安全跨越 managed/unmanaged 边界的数据结构，并用编译期断言守护契约。",
    careerValue: "数据布局契约能力，是区分“会调 API”与“懂边界”的关键证据。",
    skillsProven: ["blittable types", "StructLayout", "static_assert", "内存契约"],
    linkedinSuggestion: "分享 static_assert + C# size check 双侧守护数据契约的做法。",
    blogSuggestion: "写《blittable：让 C# 和 C++ 对同一块内存说同一种语言》。",
    portfolioSuggestion: "展示双侧 struct 定义对照与校验代码截图。",
    resumeBullet: "设计 blittable 跨边界数据契约，以 C++ static_assert 与 C# 尺寸校验双侧锁定内存布局。",
    interviewExplanation: "我能设计安全跨越 managed/unmanaged 边界的数据结构。",
    icon: "contract",
  },
  {
    id: "art_m5",
    name: "批处理原生步进",
    nameEn: "Batched Native Step",
    rarity: "rare",
    sourceQuestId: "m5",
    proves: "你懂得用批量调用摊薄边界穿越成本，并用 checksum 验证正确性。",
    careerValue: "批处理是 interop 性能的第一原则，你有可运行的正面样本。",
    skillsProven: ["批处理设计", "NativeArray 边界", "checksum 验证"],
    linkedinSuggestion: "分享一图流：一次批量调用 vs N 次单独调用的调用次数对比。",
    blogSuggestion: "写《interop 性能第一课：把 N 次穿越变成 1 次》。",
    portfolioSuggestion: "附 agent swarm 运动 GIF 与每帧调用计数。",
    resumeBullet: "实现批量化 native 步进接口，单次 P/Invoke 更新全量 agent，以 checksum 保证跨模式一致性。",
    interviewExplanation: "我刻意使用批量调用来避免逐实体的边界开销。",
    icon: "batch",
  },
  {
    id: "art_m6",
    name: "反模式标本",
    nameEn: "Anti-pattern Specimen",
    rarity: "epic",
    sourceQuestId: "m6",
    proves: "你能构造受控的反面实验，证明天真的 native 集成可能比 C# 更糟。",
    careerValue: "能拿出反例的工程师，比只会说“最佳实践”的工程师可信十倍。",
    skillsProven: ["对照实验设计", "边界成本机理", "trade-off 表达"],
    linkedinSuggestion: "发布对照数据：per-agent P/Invoke 为什么会输给纯 C#。",
    blogSuggestion: "写《我故意写了一段坏代码：per-agent P/Invoke 解剖》。",
    portfolioSuggestion: "展示 ANTI-PATTERN 标注的 UI 截图与调用次数对比表。",
    resumeBullet: "构建 per-agent P/Invoke 反模式对照组，量化逐实体边界穿越的性能惩罚。",
    interviewExplanation: "我能演示为什么天真的 native 集成可能比 C# 更糟。",
    icon: "specimen",
  },
  {
    id: "art_m7",
    name: "边界成本报告",
    nameEn: "Boundary Cost Report",
    rarity: "epic",
    sourceQuestId: "m7",
    proves: "你能设计并测量 managed/native interop 成本，而不是靠猜。",
    careerValue: "一份方法论严谨的基准报告，是性能工程能力最硬的通货。",
    skillsProven: ["benchmark 方法论", "median/p95", "GC alloc 测量", "HUD 工具"],
    linkedinSuggestion: "起草一篇帖子：解释为什么 per-agent P/Invoke 是反模式、为什么批处理重要。",
    blogSuggestion: "写基准方法论长文：固定 seed、warmup、median/p95、GC alloc、渲染隔离。",
    portfolioSuggestion: "加入基准截图、CSV 样本与方法论摘要。",
    resumeBullet:
      "构建 Agent Swarm 基准，对比 managed C#、Burst、native per-call P/Invoke 与 native batched 执行，输出 median/p95、GC allocation、checksum 校验与 CSV 导出。",
    interviewExplanation: "我测量 interop，而不是猜测。",
    icon: "report",
  },
  {
    id: "art_m8",
    name: "公平试炼之印",
    nameEn: "Fairness Trial Seal",
    rarity: "epic",
    sourceQuestId: "m8",
    proves: "你与 Unity 自己的高性能路径公平对比，拒绝 C++ 崇拜。",
    careerValue: "克制而公平的结论让你的全部数据都更可信——这是资深工程师的signature。",
    skillsProven: ["Jobs/Burst", "公平基准设计", "技术诚实"],
    linkedinSuggestion: "分享 Burst 与 native batched 的真实对比数据与你的克制结论。",
    blogSuggestion: "写《在宣称 C++ 更快之前，先打赢 Burst》。",
    portfolioSuggestion: "展示四模式完整对比表，突出公平性设计。",
    resumeBullet: "引入 C# Jobs + Burst 基线，确保 native 性能结论经受 Unity 高性能路径的公平对比。",
    interviewExplanation: "我不宣称 C++ 自动更快；我拿它与 Unity 自己的高性能路径对比。",
    icon: "seal",
  },
  {
    id: "art_m9",
    name: "内存布局法典",
    nameEn: "Memory Layout Codex",
    rarity: "epic",
    sourceQuestId: "m9",
    proves: "你理解数据布局与边界契约的深层机制，而不只是语法。",
    careerValue: "AoS/SoA 与对齐知识直接对标系统/引擎岗位的硬性要求。",
    skillsProven: ["AoS/SoA", "对齐与 padding", "pointer 契约"],
    linkedinSuggestion: "分享布局实验的一个反直觉发现（例如 Pack=1 何时更慢）。",
    blogSuggestion: "写《Pack=1 不是魔法：一次真实的布局实验》。",
    portfolioSuggestion: "附布局对比表与报告链接。",
    resumeBullet: "完成 AoS/SoA、natural/packed、copy/pointer 布局对照实验，产出内存布局研究报告。",
    interviewExplanation: "我理解数据布局与边界契约，不只是语法。",
    icon: "codex",
  },
  {
    id: "art_m10",
    name: "可恢复失败协议",
    nameEn: "Recoverable Failure Protocol",
    rarity: "epic",
    sourceQuestId: "m10",
    proves: "你能为 native 库设计完整的失败模型：可恢复、可诊断、有边界。",
    careerValue: "失败路径设计是生产级与 demo 级的分水岭，也是面试高频深水区。",
    skillsProven: ["ResultCode 设计", "异常边界", "失败注入测试", "诊断工具"],
    linkedinSuggestion: "分享你的失败注入清单与 wrapper 的安全边界声明。",
    blogSuggestion: "写《native 异常为什么不能跨 C ABI，以及怎么办》。",
    portfolioSuggestion: "展示诊断 HUD 截图与失败注入测试列表。",
    resumeBullet: "设计 ResultCode + LastError 错误边界与日志回调，以失败注入测试验证 native 库的可恢复性。",
    interviewExplanation: "wrapper 让 native 代码可以被 gameplay 代码更安全地消费。",
    icon: "protocol",
  },
  {
    id: "art_m11",
    name: "面向开发者的包",
    nameEn: "Developer-Facing Package",
    rarity: "legendary",
    sourceQuestId: "m11",
    proves: "你能交付面向开发者的 Unity 工具，通过全新工程验证。",
    careerValue: "从“会写代码”到“会交付工具”的跨越，直接对标 Runtime Tooling 岗位。",
    skillsProven: ["UPM 打包", "asmdef 架构", "Samples 设计", "开发者体验"],
    linkedinSuggestion: "宣布包发布：quickstart GIF + Samples 说明。",
    blogSuggestion: "写《把一个 native 集成打包成人人可用的 UPM 包》。",
    portfolioSuggestion: "作品集加入包结构图与 quickstart 段落。",
    resumeBullet: "交付带 Runtime/Editor asmdef 与双 Samples 的 UPM 包，经全新 Unity 工程导入验证。",
    interviewExplanation: "我能交付面向开发者的 Unity 工具，而不只是场景 demo。",
    icon: "package",
  },
  {
    id: "art_m12",
    name: "移动边界通行证",
    nameEn: "Mobile Boundary Passage",
    rarity: "legendary",
    sourceQuestId: "m12",
    proves: "你验证了移动端 native 打包的完整链路，连接了你的移动生产背景。",
    careerValue: "移动生产经验 × native 边界能力的组合，在 Unity 生态里非常稀缺。",
    skillsProven: ["Android ARM64 交叉编译", "IL2CPP", "插件导入设置"],
    linkedinSuggestion: "分享 Android IL2CPP 验证记录：阻塞点与修复路径。",
    blogSuggestion: "写《把 native 库带上 Android：一份 IL2CPP 生存笔记》。",
    portfolioSuggestion: "附构建日志摘要与 ABI 目录结构说明。",
    resumeBullet: "完成 Android ARM64 native 库交叉编译与 Unity IL2CPP development build 验证。",
    interviewExplanation: "我验证了移动端 native 打包，这与我的 Unity 移动背景直接相连。",
    icon: "passage",
  },
  {
    id: "art_m13",
    name: "引擎近郊观测台",
    nameEn: "Engine-Adjacent Observatory",
    rarity: "legendary",
    sourceQuestId: "m13",
    proves: "你在核心稳固后探索了 engine/XR 相邻扩展点，并守住了架构边界。",
    careerValue: "展示受控的好奇心：能探索前沿，也能不让探索破坏主线。",
    skillsProven: ["render-thread 事件 / XR 诊断", "架构边界自律"],
    linkedinSuggestion: "分享可选扩展 demo 与它的局限性说明——克制本身就是亮点。",
    blogSuggestion: "写《核心稳固之后，我才允许自己碰 XR/渲染线程》。",
    portfolioSuggestion: "附 demo GIF 与“不重写核心”的架构说明。",
    resumeBullet: "在核心边界架构稳定后，实现 XR 位姿诊断 / render-thread 事件扩展示例并明确其边界。",
    interviewExplanation: "我在核心桥梁稳固之后，探索了 engine/XR 相邻的扩展点。",
    icon: "observatory",
  },
];

export const ARTIFACT_BY_ID: Record<string, Artifact> = Object.fromEntries(ARTIFACTS.map((a) => [a.id, a]));
