import type { Campaign, Region } from "@/types/domain";

/**
 * 世界结构：主线三幕 + 可选的生产经验营地（Act 0 支线）。
 * Act II / III 在 MVP 中仅作为迷雾中的剪影存在（无任务内容）。
 * 营地是支线：不参与线性迷雾链，点燃炉火后即开放，永不阻塞主线。
 */

export const CAMPAIGNS: Campaign[] = [
  {
    id: "act1",
    order: 1,
    name: "第一幕 · 边界学徒",
    nameEn: "ACT I: The Boundary Apprentice",
    tagline: "让 Unity 听见 native runtime 的声音，并证明每一步。",
    regionIds: [
      "hearth_hall",
      "bridge_village",
      "benchmark_plains",
      "layout_archives",
      "safety_clinic",
      "package_harbor",
      "mobile_gate",
      "observatory_annex",
    ],
  },
  {
    id: "act0",
    order: 2,
    name: "营地 · 整理旧装备",
    nameEn: "BASECAMP: Production Experience",
    tagline: "把五年 Unity 生产直觉变成有名字的证据。可选支线，永不阻塞主线。",
    regionIds: ["production_basecamp"],
  },
  {
    id: "act2",
    order: 3,
    name: "第二幕 · 内核铸造者",
    nameEn: "ACT II: The Kernel Builder",
    tagline: "在 Unity 之外，铸造一个可复现的确定性仿真内核。",
    regionIds: [
      "fixed_timestep_garden",
      "input_log_workshop",
      "state_hash_tower",
      "snapshot_keep",
      "replay_chamber",
      "headless_cli_arena",
      "unity_visualizer_bridge",
    ],
  },
  {
    id: "act3",
    order: 4,
    name: "第三幕 · 确定性架构师",
    nameEn: "ACT III: The Determinism Architect",
    tagline: "从内核到基础设施，从证据到职业身份。",
    regionIds: [
      "multi_agent_lab",
      "replay_observatory",
      "debug_timeline_cathedral",
      "sim_infra_citadel",
      "portfolio_hall",
    ],
  },
];

export const REGIONS: Region[] = [
  // ---- ACT I ----
  {
    id: "hearth_hall",
    actId: "act1",
    order: 0,
    name: "炉火大厅",
    nameEn: "Hearth Hall",
    vibe: "温暖的炉火、木桌与地图，一切旅程从这里开始。",
    description: "学院的家。在这里点燃你的转型宣言，领取第一个任务。",
    icon: "hearth",
  },
  {
    id: "bridge_village",
    actId: "act1",
    order: 1,
    name: "边界新手村",
    nameEn: "Bridge Village",
    vibe: "一座横跨 managed 与 native 世界的石桥小村。",
    description: "搭好脚手架，让 native runtime 发出第一句回应，并建立所有权契约。",
    bossQuestId: "boss_bridge",
    icon: "bridge",
  },
  {
    id: "benchmark_plains",
    actId: "act1",
    order: 2,
    name: "基准测试平原",
    nameEn: "Benchmark Plains",
    vibe: "开阔的草原上竖立着测量石碑，风里都是数据。",
    description: "定义 blittable 数据契约，构建 Agent Swarm 基准，用数据代替猜测。",
    bossQuestId: "boss_benchmark",
    icon: "plains",
  },
  {
    id: "layout_archives",
    actId: "act1",
    order: 3,
    name: "布局档案馆",
    nameEn: "Layout Archives",
    vibe: "高耸的档案架上排列着内存布局的古老卷轴。",
    description: "AoS/SoA、natural/packed、copy/pointer——理解数据在边界两侧的真实形状。",
    bossQuestId: "boss_layout",
    icon: "archives",
  },
  {
    id: "safety_clinic",
    actId: "act1",
    order: 4,
    name: "安全边界诊所",
    nameEn: "Safety Clinic",
    vibe: "干净明亮的诊室，专治跨边界的失败与异常。",
    description: "ResultCode、LastError、日志回调与失败注入——让 native 代码可以被安全消费。",
    bossQuestId: "boss_safety",
    icon: "clinic",
  },
  {
    id: "package_harbor",
    actId: "act1",
    order: 5,
    name: "包管理港口",
    nameEn: "Package Harbor",
    vibe: "吊车与集装箱之间，工具以包裹的形式起航。",
    description: "把 runtime/editor 代码装进干净的 UPM 包，让别的开发者能直接使用。",
    bossQuestId: "boss_package",
    icon: "harbor",
  },
  {
    id: "mobile_gate",
    actId: "act1",
    order: 6,
    name: "移动端之门",
    nameEn: "Mobile Gate",
    vibe: "石门上刻着 ARM64 的纹章，通往真实设备的世界。",
    description: "Android ARM64 + IL2CPP 验证，把边界工程带回你熟悉的移动端战场。",
    bossQuestId: "boss_mobile",
    icon: "gate",
  },
  {
    id: "observatory_annex",
    actId: "act1",
    order: 7,
    name: "观测台附楼",
    nameEn: "Observatory Annex",
    vibe: "塔顶的望远镜指向引擎更深处的星空。",
    description: "可选的晚期扩展：XR 位姿诊断或 render-thread 事件示例。",
    icon: "observatory",
  },
  // ---- BASECAMP（Act 0 支线：整理旧装备） ----
  {
    id: "production_basecamp",
    actId: "act0",
    order: 0,
    name: "生产经验营地",
    nameEn: "Production Basecamp",
    vibe: "帐篷里摊开五年的旧装备——每一件都比你以为的更值钱。",
    description: "把 Unity 移动生产的隐性经验整理成显性证据：盘点、心智模型、热路径规则、职业叙事。可选，不阻塞主线。",
    icon: "camp",
    side: true,
  },
  // ---- ACT II（迷雾中的剪影） ----
  {
    id: "fixed_timestep_garden",
    actId: "act2",
    order: 0,
    name: "固定时间步花园",
    nameEn: "Fixed Timestep Garden",
    vibe: "每一片叶子都以完全相同的节拍生长。",
    description: "Act II 内容，完成第一幕后铸造。",
    icon: "garden",
  },
  {
    id: "input_log_workshop",
    actId: "act2",
    order: 1,
    name: "输入日志工坊",
    nameEn: "Input Log Workshop",
    vibe: "所有指令都被誊写进不会说谎的日志。",
    description: "Act II 内容。",
    icon: "workshop",
  },
  {
    id: "state_hash_tower",
    actId: "act2",
    order: 2,
    name: "状态哈希之塔",
    nameEn: "State Hash Tower",
    vibe: "塔上的钟声为每一帧状态盖下指纹。",
    description: "Act II 内容。",
    icon: "tower",
  },
  {
    id: "snapshot_keep",
    actId: "act2",
    order: 3,
    name: "快照要塞",
    nameEn: "Snapshot Keep",
    vibe: "时间在这里可以被封存、取出、复原。",
    description: "Act II 内容。",
    icon: "keep",
  },
  {
    id: "replay_chamber",
    actId: "act2",
    order: 4,
    name: "回放密室",
    nameEn: "Replay Chamber",
    vibe: "同样的输入，永远得到同样的历史。",
    description: "Act II 内容。",
    icon: "chamber",
  },
  {
    id: "headless_cli_arena",
    actId: "act2",
    order: 5,
    name: "无头 CLI 竞技场",
    nameEn: "Headless CLI Arena",
    vibe: "没有画面，只有纯粹的仿真在奔跑。",
    description: "Act II 内容。",
    icon: "arena",
  },
  {
    id: "unity_visualizer_bridge",
    actId: "act2",
    order: 6,
    name: "Unity 可视化之桥",
    nameEn: "Unity Visualizer Bridge",
    vibe: "内核与画面在此重逢。",
    description: "Act II 内容。",
    icon: "bridge2",
  },
  // ---- ACT III（深雾） ----
  {
    id: "multi_agent_lab",
    actId: "act3",
    order: 0,
    name: "多智能体实验室",
    nameEn: "Multi-Agent Scenario Lab",
    vibe: "成千上万的意志在同一时间线上交织。",
    description: "Act III 内容。",
    icon: "lab",
  },
  {
    id: "replay_observatory",
    actId: "act3",
    order: 1,
    name: "回放观测台",
    nameEn: "Replay Viewer Observatory",
    vibe: "在望远镜里检视每一帧历史。",
    description: "Act III 内容。",
    icon: "observatory2",
  },
  {
    id: "debug_timeline_cathedral",
    actId: "act3",
    order: 2,
    name: "调试时间线大教堂",
    nameEn: "Debug Timeline Cathedral",
    vibe: "彩窗上绘着 bug 被光芒逐帧定位的圣迹。",
    description: "Act III 内容。",
    icon: "cathedral",
  },
  {
    id: "sim_infra_citadel",
    actId: "act3",
    order: 3,
    name: "仿真基础设施城塞",
    nameEn: "Simulation Infrastructure Citadel",
    vibe: "为他人的仿真世界提供地基的城。",
    description: "Act III 内容。",
    icon: "citadel",
  },
  {
    id: "portfolio_hall",
    actId: "act3",
    order: 4,
    name: "作品集荣誉殿堂",
    nameEn: "Portfolio Hall of Fame",
    vibe: "你锻造过的一切证据在此陈列发光。",
    description: "Act III 内容。",
    icon: "hall",
  },
];

export const REGION_BY_ID: Record<string, Region> = Object.fromEntries(REGIONS.map((r) => [r.id, r]));

export const CAMPAIGN_BY_ID: Record<string, Campaign> = Object.fromEntries(CAMPAIGNS.map((c) => [c.id, c]));

/** 跨幕的全局区域顺序（迷雾推导用） */
export const ORDERED_REGIONS: Region[] = CAMPAIGNS.slice()
  .sort((a, b) => a.order - b.order)
  .flatMap((c) => REGIONS.filter((r) => r.actId === c.id).sort((a, b) => a.order - b.order));
