import type { Quest } from "@/types/domain";

/**
 * Unity Native Boundary Lab — 全部任务种子内容。
 * R0 引导任务 + M0–M8 里程碑 + 2 座 Boss 之门 + 生产经验营地（B1–B6）。
 *
 * 战略修订（2026-07-12）：主线在 boss_benchmark（Public Demo Slice）止步。
 * 旧 M9–M13 与其 4 座 Boss 之门（内存布局/安全边界/UPM 打包/Android/XR）已随
 * career-strategy.md 的范围裁决整体删除——它们服务于已废弃的
 * 「Unity native/SDK/tools 职业锚点」叙事。Act II（应用物理）/ Act III（可复现性）
 * 的任务内容将在主线收工后铸造。
 */

function forgePrompt(code: string, title: string, goal: string, extra?: string): string {
  return `你是我的结对工程师。现在只帮我完成 Unity Native Boundary Lab ${code} — ${title}。

不要跳到后续里程碑，不要引入 XR、Android、SIMD、render-thread 或完整确定性仿真内核。

我的目标：
${goal}

请按以下结构引导我：
1. 概念图（这一步涉及哪些概念，它们如何关联）
2. 文件改动清单
3. 实现步骤
4. 验证方法
5. 调试检查清单
6. 性能注意事项
7. 面试解释（我该如何讲述这一步）
8. Commit message 建议

保持范围克制。${extra ?? ""}`;
}

const EARLY_FORBIDDEN = [
  "不要做 XR。",
  "不要做 Android。",
  "不要做 SIMD。",
  "不要做 render thread。",
  "不要做 Unreal mirror。",
  "不要做完整 deterministic simulation kernel。",
  "不要随机打开新课程，除非它解决当前任务卡点。",
];

export const QUESTS: Quest[] = [
  // ------------------------------------------------------------
  // R0 — 点燃炉火（引导任务）
  // ------------------------------------------------------------
  {
    id: "q_r0",
    code: "R0",
    title: "点燃炉火",
    regionId: "hearth_hall",
    type: "reflection",
    order: 0,
    narrativeHook: "炉火不是装饰。它代表你愿意把模糊野心铸造成可验证的证据。",
    objective: "确认转职路线与当前主线项目，接受证据规则，解锁边界新手村。",
    whyItMatters:
      "在铸造任何东西之前，你必须知道这套系统在为哪一场身份转变服务。当未来某天你在 ABI 边界的调试泥潭里怀疑自己时，今天写下的一句话是你回来的路标。",
    prerequisites: [],
    definitionOfDone: [
      "读完转职路径图，理解四个阶段的含义。",
      "确认当前主线项目：Unity Native Boundary Lab。",
      "写下一句话：你正在试图成为什么。",
      "接受证据规则：No artifact, no mastery XP。",
    ],
    evidenceRequired: [
      {
        id: "intention",
        type: "text_reflection",
        label: "一句话意图（你正在试图成为什么）",
        placeholder: "例如：我正在从 Unity 生产工程师，先以 Unity/实时 3D 桥接进入仿真行业，再走向能为仿真结果的可靠性负责的可信仿真基础设施工程师。",
        multiline: true,
      },
      {
        id: "main_project",
        type: "text_reflection",
        label: "当前主线项目（亲手写下它的名字）",
        placeholder: "Unity Native Boundary Lab",
      },
      {
        id: "reflection",
        type: "text_reflection",
        label: "可选反思：为什么是现在？",
        placeholder: "此刻做这场转型的私人理由（只写给自己看）",
        multiline: true,
        optional: true,
      },
    ],
    skills: ["skill_evidence_progression", "skill_career_north_star"],
    artifactIds: ["art_r0"],
    rewards: { xp: 40, gold: 40, skillPoints: 2, reputation: 0, insight: 0 },
    aiPrompt: forgePrompt(
      "R0",
      "点燃炉火",
      "梳理我的职业转型路径：Unity Mobile Production Engineer → 仿真行业里的 Unity/实时 3D 桥梁工程师（Stage 1，立即优先）→ 仿真平台/验证/回归工程师（Stage 2，2-4 年目标）→ 可信仿真基础设施工程师（North Star：为 Physical AI、机器人、数字孪生、训练仿真的可靠性负责）。确定性是这条路径上的核心方法，不是终点职位。帮我把这条路径压缩成一句『我正在试图成为什么』的意图宣言，并解释为什么 Unity Native Boundary Lab（作为支撑性证据，已裁剪至最小公开切片）和后续的 MuJoCo 可复现性项目分别在这条路径上扮演什么角色。",
    ),
    resources: [
      { label: "roadmap.sh / C++", url: "https://roadmap.sh/cpp", note: "只看地图全貌，不要开始学习" },
    ],
    commonTraps: [
      "把宣言写成一篇长文。一句话就够。",
      "在第一天就制定完美计划。计划由任务系统承担。",
      "跳过仪式直接写代码——没有北极星的代码会跑偏。",
    ],
    interviewExplanation:
      "我用一套系统把项目工作转化为显性证据，支撑从 Unity 生产开发先桥接进入仿真行业、再走向可信仿真基础设施工程师的转型。",
    nextRisk: "仪式感之后最怕停留。下一步直接创建仓库脚手架（M0），不要再『准备』。",
    unlocks: ["m0"],
    estimate: "10–15 分钟",
    conceptMap: [
      "Unity Production Engineer",
      "Boundary Apprentice（边界学徒，支撑性证据）",
      "Simulation-Industry Bridge Engineer（仿真行业桥梁工程师，Stage 1）",
      "Trusted Simulation Infrastructure Engineer（可信仿真基础设施工程师，North Star）",
    ],
    filesToCreate: [
      "不需要写代码。",
      "一句话意图宣言（写进下方证据栏）。",
      "当前主线项目确认。",
      "可选：一段私人反思。",
    ],
    steps: [
      "读一遍上方的转职路径概念链，找到你现在站的位置。",
      "确认当前主线项目：Unity Native Boundary Lab。",
      "用一句话写下你正在试图成为什么。",
      "接受证据规则：No artifact, no mastery XP。",
      "提交证据，点燃炉火。",
    ],
    debuggingNotes: [
      "如果一句话写不出来：先写三句，再删掉两句最不痛的。",
      "如果对路径有怀疑：怀疑本身写进可选反思，它是证据不是障碍。",
    ],
    publicShowcaseSeed: "此刻还不公开。这是内在的身份锚点——它会在 M0 变成 README 的第一段 thesis。",
  },

  // ------------------------------------------------------------
  // M0 — 项目脚手架
  // ------------------------------------------------------------
  {
    id: "m0",
    code: "M0",
    title: "项目脚手架",
    regionId: "bridge_village",
    type: "main",
    order: 1,
    narrativeHook: "桥梁不是从第一行复杂代码开始的。它从边界、结构、命名和 thesis 开始。",
    objective: "创建 Unity Native Boundary Lab 的仓库脚手架。",
    whyItMatters:
      "这一步证明你把项目定位为严肃的边界研究（boundary research），而不是一个随手的 native DLL demo。清晰的结构会在后续每一个里程碑里持续回报你。",
    prerequisites: ["q_r0"],
    definitionOfDone: [
      "GitHub 仓库存在，或本地 repo 已初始化。",
      "目录存在：native/、unity/、docs/。",
      "README 包含一段论文式 thesis（一段话）。",
      "docs 骨架存在。",
      "Unity 工程目录存在。",
      "完成第一次 commit。",
    ],
    evidenceRequired: [
      { id: "commit", type: "commit_hash", label: "Commit Hash", placeholder: "例如 a1b2c3d" },
      {
        id: "tree",
        type: "screenshot_note",
        label: "仓库结构（截图路径或文本树）",
        placeholder: "粘贴 tree 输出或截图路径",
        multiline: true,
      },
      {
        id: "thesis",
        type: "doc_section",
        label: "README thesis 段落",
        placeholder: "粘贴你的一段话 thesis",
        multiline: true,
      },
      {
        id: "reflection",
        type: "text_reflection",
        label: "3 行反思",
        placeholder: "今天做对了什么 / 卡在哪里 / 明天第一步",
        multiline: true,
      },
    ],
    skills: ["skill_project_scoping", "skill_repo_scaffold", "skill_tech_thesis"],
    artifactIds: ["art_m0"],
    rewards: { xp: 80, gold: 60, skillPoints: 2, reputation: 5, insight: 0 },
    aiPrompt: forgePrompt(
      "M0",
      "项目脚手架",
      "创建 Unity Native Boundary Lab 仓库：native/、unity/、docs/ 三个顶层目录，README 一段话 thesis（Native C++ 不自动等于更快；边界设计、批处理、布局、生命周期与诊断决定 interop 是助力还是拖累），docs 骨架（ARCHITECTURE.md / INTEROP_DESIGN.md / BENCHMARK_METHODOLOGY.md），Unity 工程目录，.gitignore，并完成首次 commit。只做 M0 —— 不要开始 M1/M2/M3。",
    ),
    resources: [
      { label: "GitHub — 新建仓库", url: "https://docs.github.com/repositories/creating-and-managing-repositories" },
    ],
    commonTraps: [
      "thesis 没想清楚就开始实现。",
      "脚手架还没搭就写太多文档。",
      "做成一个普通 Unity demo。",
      "过早启动 XR、Android、SIMD 或 render-thread。",
      "打开随机课程，而不是创建仓库。",
    ],
    interviewExplanation: "我把项目定位为边界研究，而不是随手的 native DLL demo。",
    nextRisk: "脚手架的整洁会诱惑你继续『完善结构』。到此为止，下一步写 CMake。",
    unlocks: ["m1"],
    forbiddenForNow: EARLY_FORBIDDEN,
    estimate: "30–60 分钟",
    conceptMap: [
      "项目 thesis",
      "仓库结构",
      "docs 骨架",
      "native 目录",
      "Unity 工程",
      "首次 commit",
    ],
    filesToCreate: [
      "README.md（第一段 = thesis）",
      "docs/ARCHITECTURE.md",
      "docs/INTEROP_DESIGN.md",
      "docs/BENCHMARK_METHODOLOGY.md",
      "native/（空目录 + 占位说明）",
      "unity/（Unity 工程目录）",
      ".gitignore",
      "首次 commit",
    ],
    steps: [
      "创建仓库或本地项目目录。",
      "创建 native/、unity/、docs/ 三个顶层目录。",
      "写 README 第一段：项目 thesis（边界设计决定 interop 成败）。",
      "添加 docs 三个骨架文件（标题 + 一句话即可）。",
      "在 ARCHITECTURE.md 里写占位的分层示意（文本即可）。",
      "添加 .gitignore（Unity + C++ 构建产物）。",
      "提交首次 commit。",
      "回到学院提交证据。",
    ],
    debuggingNotes: [
      "仓库结构感到混乱时，回到 thesis：这是 Unity ↔ C++ 边界实验室。",
      "docs 越写越大时，保留骨架立即前进——M0 要的是地基，不是完整性。",
    ],
    publicShowcaseSeed: "还不是 LinkedIn 帖子。它播种的是 GitHub README 与整个项目的定位——严肃的边界研究。",
  },

  // ------------------------------------------------------------
  // M1 — CMake 原生库
  // ------------------------------------------------------------
  {
    id: "m1",
    code: "M1",
    title: "CMake 原生库",
    regionId: "bridge_village",
    type: "main",
    order: 2,
    narrativeHook: "Unity 还不能听见任何东西，直到 native runtime 先能独立发声。",
    objective: "用 CMake 构建一个导出 NblGetVersionMajor/Minor/Patch 的原生库。",
    whyItMatters:
      "能在 Unity 之外独立构建 native 二进制，是『边界工程师』与『只会拖 DLL 的人』的分水岭。你将第一次直面编译、链接与符号导出。",
    prerequisites: ["m0"],
    definitionOfDone: [
      "CMake 工程可构建。",
      "产出原生库 artifact（.dll / .dylib / .so）。",
      "nbl_api.h 与 nbl_api.cpp 存在。",
      "NblGetVersionMajor/Minor/Patch 已导出。",
      "native 冒烟测试或手动验证确认版本函数存在。",
      "Unity plugin 文件位置已准备好。",
    ],
    evidenceRequired: [
      { id: "commit", type: "commit_hash", label: "Commit Hash", placeholder: "例如 a1b2c3d" },
      {
        id: "build_log",
        type: "screenshot_note",
        label: "构建输出（截图路径或日志片段）",
        placeholder: "粘贴构建成功的关键日志",
        multiline: true,
      },
      {
        id: "debug_release",
        type: "text_reflection",
        label: "Debug vs Release 简要说明",
        placeholder: "两种配置差异是什么？基准测试应该用哪个？",
        multiline: true,
      },
      {
        id: "failure_note",
        type: "text_reflection",
        label: "一条失败/调试记录（如有）",
        placeholder: "记录一次报错与你的解法",
        multiline: true,
        optional: true,
      },
    ],
    skills: ["skill_cmake", "skill_header_source", "skill_symbol_export", "skill_extern_c", "skill_c_abi", "skill_compilation", "skill_linking"],
    artifactIds: ["art_m1"],
    rewards: { xp: 120, gold: 70, skillPoints: 3, reputation: 0, insight: 0 },
    aiPrompt: forgePrompt(
      "M1",
      "CMake 原生库",
      "创建一个 CMake 工程，构建名为 nbl 的共享库；nbl_api.h 声明并导出 NblGetVersionMajor/Minor/Patch 三个 C 函数（注意导出宏与 extern \"C\"）；nbl_api.cpp 实现它们；提供一个最小的 native 冒烟测试（可执行文件或脚本）验证符号存在。",
    ),
    resources: [
      { label: "CMake 官方教程", url: "https://cmake.org/cmake/help/latest/guide/tutorial/index.html", note: "只看 Step 1–2" },
      { label: "learncpp — 编译与链接", url: "https://www.learncpp.com/cpp-tutorial/introduction-to-the-compiler-linker-and-libraries/" },
    ],
    commonTraps: [
      "忘记导出宏（__declspec(dllexport) / visibility）。",
      "C++ name mangling 吃掉了你的符号。",
      "构建产物路径搞错，找不到 .dll/.dylib/.so。",
      "头文件与实现不分离。",
      "native 构建还没验证就假设 Unity 能加载它。",
      "把 Debug 冒烟测试当成 Release 基准就绪。",
    ],
    interviewExplanation: "我可以在 Unity 之外构建 native 库，并对二进制产物进行推理。",
    nextRisk: "构建成功的兴奋会让你想立刻加功能。先让 Unity 听见它（M2），再谈其他。",
    unlocks: ["m2"],
    forbiddenForNow: [
      "不要做 M2 P/Invoke，除非 M1 build 已经稳定。",
      "不要做 benchmark。",
      ...EARLY_FORBIDDEN,
    ],
    estimate: "60–120 分钟",
    conceptMap: [
      "CMake 工程",
      "nbl_api.h",
      "导出宏",
      'extern "C"',
      "版本函数",
      "构建产物",
      "Unity 插件位置预备",
    ],
    filesToCreate: [
      "native/CMakeLists.txt",
      "native/include/nbl_api.h",
      "native/src/nbl_api.cpp",
      "可选：native 冒烟测试（可执行或脚本）",
      "构建输出目录（build/）",
      "docs 里一条 native 构建笔记",
    ],
    steps: [
      "创建 native/CMakeLists.txt，定义共享库 nbl。",
      "创建 native/include/nbl_api.h。",
      "定义跨平台导出宏（Windows dllexport / 其他 visibility）。",
      '把导出函数包进 extern "C"。',
      "声明 NblGetVersionMajor / Minor / Patch。",
      "创建 native/src/nbl_api.cpp 实现三个函数。",
      "构建 Debug。",
      "可能的话构建 Release。",
      "记录构建输出（产物路径与文件名）。",
      "提交 commit，回学院交证据。",
    ],
    debuggingNotes: [
      "符号缺失：检查导出宏与 extern \"C\"，用 dumpbin /EXPORTS 或 nm 验证。",
      "CMake configure 失败：检查编译器/工具链路径（VS Build Tools、CMake 版本）。",
      "构建产物路径混乱：先把路径记进文档，不要盲目移动二进制文件。",
    ],
    publicShowcaseSeed: "这一步会成为未来 GitHub README 的 quickstart 与架构解释的一部分：native runtime 独立构建、版本信号先行。",
  },

  // ------------------------------------------------------------
  // M2 — 第一次 P/Invoke 调用
  // ------------------------------------------------------------
  {
    id: "m2",
    code: "M2",
    title: "第一次 P/Invoke 调用",
    regionId: "bridge_village",
    type: "main",
    order: 3,
    narrativeHook: "native runtime 已经能说话了。今天的任务是让 Unity 听见它。",
    objective: "在 Unity C# 中通过 DllImport 调用 NblGetVersionMajor/Minor/Patch。",
    whyItMatters:
      "这是 managed 世界与 unmanaged 世界的第一次握手。理解 Unity 如何发现并调用非托管函数，是后面一切边界工作的地基。",
    prerequisites: ["m1"],
    definitionOfDone: [
      "C# DllImport 声明可编译。",
      "原生库放置在 Unity 能加载的位置。",
      "Unity Editor 场景打印出 native 版本号。",
      "失败案例被干净地记录下来。",
      "你能解释为什么 extern \"C\" 是必要的。",
    ],
    evidenceRequired: [
      { id: "commit", type: "commit_hash", label: "Commit Hash", placeholder: "例如 a1b2c3d" },
      {
        id: "editor_shot",
        type: "screenshot_note",
        label: "Unity Editor 截图（路径或说明）",
        placeholder: "Console 打印版本号的截图路径",
      },
      {
        id: "debug_note",
        type: "text_reflection",
        label: "DLL 加载或符号问题的调试记录",
        placeholder: "例如 EntryPointNotFoundException 的排查过程",
        multiline: true,
      },
      {
        id: "explain_90s",
        type: "text_reflection",
        label: "90 秒文字讲解",
        placeholder: "向面试官解释：Unity 是如何找到并调用这个 native 函数的？",
        multiline: true,
      },
    ],
    skills: ["skill_extern_c", "skill_plugin_loading", "skill_dllimport", "skill_dynlib", "skill_abi"],
    artifactIds: ["art_m2"],
    rewards: { xp: 140, gold: 80, skillPoints: 3, reputation: 0, insight: 0 },
    aiPrompt: forgePrompt(
      "M2",
      "第一次 P/Invoke 调用",
      "Unity C# 通过 DllImport 调用 native 的 NblGetVersionMajor/Minor/Patch，并在 Unity Editor 中打印版本号。",
    ),
    resources: [
      { label: "Unity — Native plug-ins", url: "https://docs.unity3d.com/Manual/NativePlugins.html" },
      { label: "Microsoft — P/Invoke", url: "https://learn.microsoft.com/dotnet/standard/native-interop/pinvoke" },
    ],
    commonTraps: [
      "缺少 extern \"C\" 导致 EntryPointNotFoundException。",
      "plugin 文件名错误（lib 前缀 / 扩展名）。",
      "架构不匹配（x64 vs ARM64）。",
      "平台导入设置未配置。",
      "把 DllImport 声明随手散落在 MonoBehaviour 里，而不是集中在 wrapper。",
    ],
    interviewExplanation: "我理解 managed Unity 代码如何发现并调用 unmanaged 函数。",
    nextRisk: "一次成功调用不等于契约。下一步（M3）要建立生命周期与所有权规则。",
    unlocks: ["m3"],
    forbiddenForNow: [
      "不要做 CreateContext/DestroyContext，除非 version call 稳定。",
      "不要做 Agent Swarm。",
      "不要做 benchmark。",
      ...EARLY_FORBIDDEN,
    ],
    estimate: "60–120 分钟",
    conceptMap: [
      "native 库",
      "Unity 插件目录",
      "DllImport",
      "managed wrapper",
      "Editor 场景 / 调试输出",
      "失败诊断",
    ],
    filesToCreate: [
      "NativeBoundary.cs（集中全部 DllImport 声明）",
      "HelloNative 示例场景或脚本",
      "插件导入设置笔记",
      "调试检查清单笔记",
    ],
    steps: [
      "把 native 库复制到 Unity 插件路径（Assets/Plugins/ 或包内 Plugins/）。",
      "新建 NativeBoundary.cs，写 DllImport 声明。",
      "添加版本号 wrapper 方法（拼接 major.minor.patch）。",
      "创建 HelloNative MonoBehaviour 或最小测试场景。",
      "在 Unity Editor 里打印 native 版本号。",
      "如果失败：完整记录异常与排查过程（它是证据，不是耻辱）。",
      "提交 commit。",
      "把截图/Console 输出作为证据提交。",
    ],
    debuggingNotes: [
      "EntryPointNotFoundException：函数名没有按预期导出——查 extern \"C\" 与拼写。",
      "DllNotFoundException：Unity 找不到或加载不了库——查文件名、位置、架构、依赖。",
      "调用即崩溃：多半是调用约定或签名不匹配。",
    ],
    publicShowcaseSeed: "这一步可以成为未来 GitHub README 里的第一张 HelloNative 截图/GIF：Unity Console 打印出 native 版本号的瞬间。",
  },

  // ------------------------------------------------------------
  // M3 — 上下文生命周期
  // ------------------------------------------------------------
  {
    id: "m3",
    code: "M3",
    title: "上下文生命周期",
    regionId: "bridge_village",
    type: "main",
    order: 4,
    narrativeHook: "桥能通还不够。真正的边界工程从 ownership 开始。",
    objective: "实现 NblCreateContext / NblDestroyContext 与 C# 侧的 NativeBoundaryContext : IDisposable 封装。",
    whyItMatters:
      "跨 ABI 泄漏 C++ 对象是无数事故的源头。opaque handle + 显式生命周期 + IDisposable，是把 native 资源装进 managed 世界的标准安全容器。",
    prerequisites: ["m2"],
    definitionOfDone: [
      "native context 可创建、可销毁。",
      "C# wrapper 私有持有 IntPtr。",
      "gameplay 层碰不到裸 native handle。",
      "双重 Dispose 是安全的。",
      "无效 handle 行为已测试或已文档化。",
      "所有权模型已写成文档。",
    ],
    evidenceRequired: [
      { id: "commit", type: "commit_hash", label: "Commit Hash", placeholder: "例如 a1b2c3d" },
      {
        id: "wrapper_code",
        type: "code_snippet",
        label: "IDisposable wrapper 代码片段或截图",
        placeholder: "粘贴 NativeBoundaryContext 关键代码",
        multiline: true,
      },
      {
        id: "ownership",
        type: "doc_section",
        label: "所有权表",
        placeholder: "谁创建 / 谁持有 / 谁销毁 / 谁不允许触碰",
        multiline: true,
      },
      {
        id: "double_dispose",
        type: "text_reflection",
        label: "双重 Dispose 验证记录",
        placeholder: "你如何验证 Dispose 两次不会崩溃？",
        multiline: true,
      },
      {
        id: "interview",
        type: "text_reflection",
        label: "简短面试回答",
        placeholder: "为什么用 opaque handle 而不是把 C++ 对象暴露给 C#？",
        multiline: true,
      },
    ],
    skills: ["skill_opaque_handle", "skill_raii", "skill_unique_ptr", "skill_intptr", "skill_idisposable", "skill_arch_explain"],
    artifactIds: ["art_m3"],
    rewards: { xp: 160, gold: 90, skillPoints: 3, reputation: 0, insight: 0 },
    aiPrompt: forgePrompt(
      "M3",
      "上下文生命周期",
      "native 侧实现 NblCreateContext / NblDestroyContext（内部用 std::unique_ptr 管理），C# 侧实现 NativeBoundaryContext : IDisposable，私有持有 IntPtr，保证双重 Dispose 安全，并写出所有权表。",
    ),
    resources: [
      { label: "Microsoft — IDisposable 模式", url: "https://learn.microsoft.com/dotnet/standard/garbage-collection/implementing-dispose" },
      { label: "learncpp — RAII / 智能指针", url: "https://www.learncpp.com/cpp-tutorial/introduction-to-smart-pointers-move-semantics/" },
    ],
    commonTraps: [
      "让 MonoBehaviour 直接持有裸 IntPtr。",
      "双重释放（double free）。",
      "Dispose 不幂等。",
      "假设 C# GC 会自动释放 native memory。",
      "让 C++ 对象直接跨越 ABI。",
      "销毁 context 两次而没有防护。",
    ],
    interviewExplanation: "我使用 opaque handle 与显式生命周期，而不是让 C++ 对象跨 ABI 泄漏。",
    nextRisk: "新手村只差最后一道门：把 M0–M3 的理解压缩成能讲出来的语言。",
    unlocks: ["boss_bridge"],
    forbiddenForNow: [
      "不要做 Agent Swarm。",
      "不要做 benchmark。",
      "不要暴露 C++ class 给 C#。",
      ...EARLY_FORBIDDEN,
    ],
    estimate: "90–150 分钟",
    conceptMap: [
      "C++ context",
      "opaque handle",
      "C ABI create/destroy",
      "C# IntPtr 持有",
      "IDisposable wrapper",
      "双重 Dispose 安全",
      "无效句柄行为",
    ],
    filesToCreate: [
      "native API 更新（nbl_api.h：NblContext + create/destroy）",
      "native context 实现（unique_ptr 管理）",
      "C# NativeBoundaryContext.cs（IDisposable）",
      "docs/INTEROP_DESIGN.md 里的所有权表",
      "简单验证场景或测试",
    ],
    steps: [
      "在 nbl_api.h 添加 NblContext 不透明句柄 typedef。",
      "声明 NblCreateContext / NblDestroyContext。",
      "C++ 侧实现 context 的分配与销毁（内部 std::unique_ptr）。",
      "C# 侧添加 DllImport 声明。",
      "实现 NativeBoundaryContext : IDisposable，私有持有 IntPtr。",
      "确保 gameplay 脚本碰不到裸 IntPtr。",
      "反复创建/销毁 context 验证稳定。",
      "测试双重 Dispose 行为（必须安全返回）。",
      "把所有权表写进 docs/INTEROP_DESIGN.md。",
      "提交 commit。",
    ],
    debuggingNotes: [
      "双重 Dispose 崩溃：Dispose 不幂等——加已释放标记并置空句柄。",
      "GC 时机影响正确性：所有权模型错了——释放必须显式，不依赖终结器时序。",
      "gameplay 脚本能看到裸 IntPtr：wrapper 边界在泄漏——收紧可见性。",
    ],
    publicShowcaseSeed: "这一步会成为 INTEROP_DESIGN.md 里最有分量的技术段落，也是未来面试防线：opaque handle + 显式生命周期的完整论证。",
  },

  // ------------------------------------------------------------
  // BOSS — 初次信号之门
  // ------------------------------------------------------------
  {
    id: "boss_bridge",
    code: "BOSS",
    title: "初次信号之门",
    regionId: "bridge_village",
    type: "boss",
    order: 5,
    narrativeHook: "你已经让桥有了地基、信号和生命周期。现在证明你能讲清楚它。",
    objective: "汇总 Bridge Village 的全部证据，回答五个边界之问，铸成桥村之印。",
    whyItMatters:
      "Boss 之门不是新代码，而是理解的凝结。能把 C ABI、opaque handle、IDisposable 讲清楚，并说出它与确定性仿真未来的关系的人，才真正拥有了这些技能——面试官也是这么想的。",
    prerequisites: ["m0", "m1", "m2", "m3"],
    definitionOfDone: [
      "M0–M3 全部完成且证据齐全（炉火誓约、奠基石、版本之石、初次信号、句柄契约五件神器在库）。",
      "写出 5 句话的 Bridge Village 总结。",
      "回答：为什么用 C ABI？",
      "回答：为什么用 opaque handle？",
      "回答：为什么用 IDisposable？",
      "回答：为什么不把 C++ class 暴露给 C#？",
      "回答：这一切与未来的确定性仿真有什么关系？",
    ],
    evidenceRequired: [
      {
        id: "summary",
        type: "text_reflection",
        label: "Bridge Village 五句总结",
        placeholder: "用 5 句话讲完从脚手架到生命周期契约的旅程",
        multiline: true,
      },
      {
        id: "why_c_abi",
        type: "text_reflection",
        label: "① 为什么用 C ABI？",
        placeholder: "你的回答……",
        multiline: true,
      },
      {
        id: "why_opaque",
        type: "text_reflection",
        label: "② 为什么用 opaque handle？",
        placeholder: "你的回答……",
        multiline: true,
      },
      {
        id: "why_idisposable",
        type: "text_reflection",
        label: "③ 为什么用 IDisposable？",
        placeholder: "你的回答……",
        multiline: true,
      },
      {
        id: "why_no_cpp_class",
        type: "text_reflection",
        label: "④ 为什么不把 C++ class 暴露给 C#？",
        placeholder: "你的回答……",
        multiline: true,
      },
      {
        id: "future_connection",
        type: "text_reflection",
        label: "⑤ 这与未来的确定性仿真有什么关系？",
        placeholder: "稳定边界 → headless 内核 → Unity 只是呈现层……",
        multiline: true,
      },
      {
        id: "defense_draft",
        type: "text_reflection",
        label: "可选：面试防线草稿（90 秒版本）",
        placeholder: "把五个回答压缩成一段 90 秒的连贯讲述",
        multiline: true,
        optional: true,
      },
    ],
    skills: ["skill_interview_defense"],
    artifactIds: ["art_boss_bridge"],
    rewards: { xp: 300, gold: 150, skillPoints: 1, reputation: 25, insight: 2 },
    aiPrompt: forgePrompt(
      "BOSS",
      "初次信号之门",
      "帮我演练五个面试问题：为什么用 C ABI？为什么用 opaque handle？为什么用 IDisposable？为什么不把 C++ class 暴露给 C#？这一切与确定性仿真的未来有什么关系？对我的回答提出改进建议，并帮我把 Bridge Village 的旅程压缩成 5 句话与一段 90 秒防线。",
      "\n你扮演一位友善但严格的系统工程面试官。",
    ),
    resources: [],
    commonTraps: ["用背诵代替理解。", "回答太长。面试回答的黄金长度是 60–90 秒。", "只讲『怎么做』，不讲『为什么』。"],
    interviewExplanation:
      "我构建并能完整解释第一座 managed/native 桥：native 构建、导出 C ABI、P/Invoke 调用、opaque context 与 managed 生命周期封装。",
    nextRisk: "平原上的数据契约（blittable）比看起来更严格。别带着'大概匹配'的心态过去。",
    unlocks: ["m4"],
    estimate: "30–45 分钟",
    conceptMap: [
      "五件神器",
      "五句总结",
      "五个边界之问",
      "面试防线",
      "桥村之印",
      "Benchmark Plains 开启",
    ],
    filesToCreate: [
      "不写新代码。",
      "Bridge Village 总结（写进证据栏）。",
      "五个问题的书面回答。",
      "可选：90 秒面试防线草稿。",
    ],
    steps: [
      "回到证据宝库，把五件神器看一遍（誓约、奠基石、版本之石、信号、句柄契约）。",
      "不看代码，用 5 句话写出这段旅程。",
      "依次回答五个边界之问，每个 3-5 句。",
      "可选：让 AI 扮演面试官对你追问，打磨出 90 秒版本。",
      "提交答辩，开启桥村之印。",
    ],
    debuggingNotes: [
      "写不出总结：按 M0 → M3 的顺序各写一句，再加一句『它证明了什么』。",
      "回答卡壳的那一问，恰恰是要回对应任务复看证据的信号。",
    ],
    publicShowcaseSeed:
      "答辩内容会沉淀为面试防线日志与 INTEROP_DESIGN.md 的总结章。它也是你第一条可考虑公开的『我造了一座桥』叙事。",
  },

  // ------------------------------------------------------------
  // M4 — Agent 数据契约
  // ------------------------------------------------------------
  {
    id: "m4",
    code: "M4",
    title: "Agent 数据契约",
    regionId: "benchmark_plains",
    type: "main",
    order: 6,
    narrativeHook: "平原上的第一块测量石碑：两个世界必须对同一块内存达成一致。",
    objective: "在 C++ 中定义 blittable 的 NblAgent，并在 C# 中定义完全匹配的 Agent struct。",
    whyItMatters:
      "跨边界传递数据的前提是两侧对字节布局的共识。static_assert 与 size check 是把这份共识写进编译器的方式——它们比任何注释都可靠。",
    prerequisites: ["boss_bridge"],
    definitionOfDone: [
      "C++ NblAgent 存在。",
      "C# 匹配的 Agent struct 存在。",
      "C++ static_assert 校验 size 与 offsets。",
      "C# size check 校验布局。",
      "README 或 docs 解释了 blittable 边界。",
    ],
    evidenceRequired: [
      { id: "commit", type: "commit_hash", label: "Commit Hash", placeholder: "例如 a1b2c3d" },
      {
        id: "cpp_assert",
        type: "code_snippet",
        label: "C++ static_assert 片段或截图",
        placeholder: "粘贴 static_assert(sizeof(NblAgent) == ...) 等",
        multiline: true,
      },
      {
        id: "cs_check",
        type: "code_snippet",
        label: "C# size check 片段或截图",
        placeholder: "粘贴 Marshal.SizeOf / sizeof 校验代码",
        multiline: true,
      },
      {
        id: "blittable_explain",
        type: "text_reflection",
        label: "blittable 的简短解释",
        placeholder: "什么样的 struct 是 blittable 的？为什么重要？",
        multiline: true,
      },
    ],
    skills: ["skill_blittable", "skill_structlayout", "skill_value_ref", "skill_stack_heap"],
    artifactIds: ["art_m4"],
    rewards: { xp: 140, gold: 80, skillPoints: 3, reputation: 0, insight: 0 },
    aiPrompt: forgePrompt(
      "M4",
      "Agent 数据契约",
      "定义 C++ NblAgent（position、velocity 等字段）与 C# [StructLayout(LayoutKind.Sequential)] Agent struct，使两者字节布局完全一致；C++ 用 static_assert 校验 size/offset，C# 侧加 size check；并解释为什么这个 struct 是 blittable 的。",
    ),
    resources: [
      { label: "Microsoft — Blittable 类型", url: "https://learn.microsoft.com/dotnet/framework/interop/blittable-and-non-blittable-types" },
      { label: "Microsoft — StructLayout", url: "https://learn.microsoft.com/dotnet/api/system.runtime.interopservices.structlayoutattribute" },
    ],
    commonTraps: [
      "在边界 struct 里使用 string、object、托管数组或引用。",
      "把 Pack=1 当成默认优化。",
      "假设 C# Vector3 与 C++ struct 永远匹配。",
    ],
    interviewExplanation: "我能设计可以安全跨越 managed/unmanaged 边界的数据结构。",
    nextRisk: "契约建立后，别急着逐个传 Agent——下一步的重点恰恰是批处理。",
    unlocks: ["m5"],
    estimate: "60–90 分钟",
    conceptMap: [
      "blittable 类型",
      "NblAgent (C++)",
      "Agent struct (C#)",
      "StructLayout.Sequential",
      "static_assert / size check",
      "布局契约文档",
    ],
    filesToCreate: [
      "native/include/nbl_api.h（NblAgent 定义）",
      "native/src 里的 static_assert 校验块",
      "unity 侧 Agent.cs（[StructLayout(LayoutKind.Sequential)]）",
      "C# 布局校验（Marshal.SizeOf 断言）",
      "docs/INTEROP_DESIGN.md 的 blittable 契约章节",
    ],
    steps: [
      "在 C++ 定义 NblAgent：position、velocity 等纯 POD 字段。",
      "用 static_assert 锁定 sizeof(NblAgent) 与关键字段 offsetof。",
      "在 C# 定义完全同序同型的 Agent struct，标注 LayoutKind.Sequential。",
      "在 C# 启动时断言 Marshal.SizeOf<Agent>() 与 native 侧一致（可通过导出 NblGetAgentSize 对表）。",
      "把『什么能进边界 struct、什么不能』写进 INTEROP_DESIGN.md。",
      "提交 commit，附上双侧断言的证据。",
    ],
    debuggingNotes: [
      "两侧 size 不一致：先查字段顺序与类型宽度，再查对齐/padding——不要急着上 Pack=1。",
      "Marshal.SizeOf 与 sizeof 不同：struct 可能不是 blittable（含 bool/char/引用类型时封送规则改变）。",
      "导出一个 NblGetAgentSize() 函数，让运行时对表代替猜测。",
    ],
    publicShowcaseSeed: "双侧编译期断言（static_assert + C# size check）的对照截图，是『把契约写进编译器』这篇博客的核心素材。",
  },

  // ------------------------------------------------------------
  // M5 — 原生批处理步进
  // ------------------------------------------------------------
  {
    id: "m5",
    code: "M5",
    title: "原生批处理步进",
    regionId: "benchmark_plains",
    type: "main",
    order: 7,
    narrativeHook: "一次渡桥，运送整支军团——而不是让每个士兵单独排队过桥。",
    objective: "实现 NblStepAgents，一次调用批量更新整个 agent 数组。",
    whyItMatters:
      "边界穿越本身有固定成本。批处理是 interop 性能的第一原则：把 N 次穿越变成 1 次。这也是后面 anti-pattern 对照实验的正面样本。",
    prerequisites: ["m4"],
    definitionOfDone: [
      "NblStepAgents 可更新一个 agent 数组。",
      "100 个 agent 更新结果正确。",
      "checksum 校验通过。",
      "每批次 native 调用次数为 1。",
      "Unity 可视化样例能展示 agent 移动或简化可视化。",
    ],
    evidenceRequired: [
      { id: "commit", type: "commit_hash", label: "Commit Hash", placeholder: "例如 a1b2c3d" },
      {
        id: "visual",
        type: "screenshot_note",
        label: "agent 运动截图/GIF 或调试输出",
        placeholder: "路径或粘贴调试输出",
      },
      {
        id: "checksum",
        type: "text_reflection",
        label: "checksum 校验记录",
        placeholder: "你如何计算并核对 checksum？",
        multiline: true,
      },
      {
        id: "batch_explain",
        type: "text_reflection",
        label: "批处理的 3 行解释",
        placeholder: "为什么一次批量调用优于 N 次单独调用？",
        multiline: true,
      },
    ],
    skills: ["skill_span", "skill_nativearray", "skill_hot_path"],
    artifactIds: ["art_m5"],
    rewards: { xp: 180, gold: 90, skillPoints: 3, reputation: 0, insight: 0 },
    aiPrompt: forgePrompt(
      "M5",
      "原生批处理步进",
      "实现 NblStepAgents(context, agents*, count, dt)：一次 P/Invoke 调用批量更新全部 agent；C# 侧用 NativeArray 或 pinned 数组传递；用 checksum 验证 100 个 agent 的更新正确性；在 Unity 中做最简可视化。",
    ),
    resources: [
      { label: "Unity — NativeArray", url: "https://docs.unity3d.com/ScriptReference/Unity.Collections.NativeArray_1.html" },
      { label: "cppreference — std::span", url: "https://en.cppreference.com/w/cpp/container/span", note: "native 内部使用" },
    ],
    commonTraps: ["每个实体一次 P/Invoke。", "渲染成本淹没仿真测量。", "没有 checksum 校验。"],
    interviewExplanation: "我刻意使用批量调用来避免逐实体的边界开销。",
    nextRisk: "下一步要故意写『坏代码』（per-agent 反模式）。记住它存在的唯一意义是对照。",
    unlocks: ["m6"],
    estimate: "90–150 分钟",
    conceptMap: [
      "NblAgent 数组",
      "NblStepAgents(ctx, agents*, count, dt)",
      "NativeArray / pinned 内存",
      "单次 P/Invoke",
      "checksum 验证",
      "最简可视化",
    ],
    filesToCreate: [
      "nbl_api.h：NblStepAgents 声明",
      "native/src/nbl_simulation.cpp（批量步进实现）",
      "C# NativeBoundary 新增声明与 wrapper",
      "AgentSwarmDemo.cs（100 agents 最简可视化）",
      "checksum 计算工具（两侧或 C# 侧）",
    ],
    steps: [
      "在 C ABI 声明 NblStepAgents(context, agents, count, dt)。",
      "C++ 内部用 std::span 包住传入内存，写朴素的位置积分。",
      "C# 用 NativeArray<Agent> 或 GCHandle pin 数组，一次调用传整批。",
      "初始化 100 个 agent（固定 seed），步进若干帧。",
      "计算 checksum（如位置分量求和）并与预期核对。",
      "在 Unity 里做最简可视化（点/方块即可，别做美术）。",
      "确认每帧 native 调用次数 == 1，提交证据。",
    ],
    debuggingNotes: [
      "数据错乱：回 M4 检查布局契约，八成是字段顺序或对齐漂移。",
      "偶发崩溃：确认数组在调用期间被 pin 住，GC 不会移动它。",
      "count 参数用元素数还是字节数？在头文件注释里写死约定。",
    ],
    publicShowcaseSeed: "100 agents 被单次调用驱动的运动 GIF + calls/frame=1 的 HUD 角标，是 README 里最有说服力的第一张动图。",
  },

  // ------------------------------------------------------------
  // M6 — 逐 Agent 反模式
  // ------------------------------------------------------------
  {
    id: "m6",
    code: "M6",
    title: "逐 Agent 反模式",
    regionId: "benchmark_plains",
    type: "main",
    order: 8,
    narrativeHook: "平原博物馆需要一个反面标本：让每个士兵单独排队过桥，然后测量队伍有多长。",
    objective: "实现 native per-agent 模式，作为基准对照的刻意反模式。",
    whyItMatters:
      "『native 不一定更快』需要证据。一个输出正确但性能糟糕的 per-agent 模式，是你论文里最有说服力的反面论据。",
    prerequisites: ["m5"],
    definitionOfDone: [
      "native per-agent 模式存在。",
      "每帧 native 调用次数 == agent 数量。",
      "输出与批处理模式在容差内一致。",
      "UI 明确标注它是反模式。",
    ],
    evidenceRequired: [
      { id: "commit", type: "commit_hash", label: "Commit Hash", placeholder: "例如 a1b2c3d" },
      {
        id: "calls_shot",
        type: "screenshot_note",
        label: "native calls/frame 截图",
        placeholder: "显示每帧调用次数的截图路径",
      },
      {
        id: "why_bad",
        type: "text_reflection",
        label: "为什么它刻意是坏的？",
        placeholder: "边界穿越成本 × N 的机制解释",
        multiline: true,
      },
      {
        id: "compare_note",
        type: "text_reflection",
        label: "与批处理路径的对照记录",
        placeholder: "相同输入下两种模式的输出一致性与调用次数对比",
        multiline: true,
      },
    ],
    skills: ["skill_tradeoff"],
    artifactIds: ["art_m6"],
    rewards: { xp: 160, gold: 90, skillPoints: 2, reputation: 5, insight: 0 },
    aiPrompt: forgePrompt(
      "M6",
      "逐 Agent 反模式",
      "实现 per-agent 模式：每帧对每个 agent 单独做一次 P/Invoke（NblStepSingleAgent）；统计每帧 native 调用次数；用相同输入数据验证输出与批处理模式在容差内一致；在 UI 上明确标注 ANTI-PATTERN。",
    ),
    resources: [
      { label: "Microsoft — 原生互操作性能", url: "https://learn.microsoft.com/dotnet/standard/native-interop/best-practices" },
    ],
    commonTraps: ["把 per-agent P/Invoke 当成推荐做法展示。", "不同模式使用不同输入数据做对比。", "忘记容差校验。"],
    interviewExplanation: "我能演示为什么天真的 native 集成可能比 C# 更糟。",
    nextRisk: "有了正反两个样本，下一步必须让测量方法本身经得起质疑（M7）。",
    unlocks: ["m7"],
    estimate: "60–90 分钟",
    conceptMap: [
      "NblStepSingleAgent",
      "每帧 N 次边界穿越",
      "封送/栈切换固定成本",
      "calls/frame 计数器",
      "输出一致性（容差）",
      "ANTI-PATTERN 标注",
    ],
    filesToCreate: [
      "nbl_api.h：NblStepSingleAgent 声明",
      "native 单实体步进实现（与批量共用核心逻辑）",
      "C# per-agent 模式驱动（每帧循环 N 次 P/Invoke）",
      "calls/frame 计数显示",
      "两模式输出对照脚本/记录",
    ],
    steps: [
      "声明 NblStepSingleAgent(context, agent*, dt)。",
      "native 内部复用与批量路径完全相同的积分逻辑（保证可对照）。",
      "C# 每帧对每个 agent 单独调用一次——故意的。",
      "统计并显示每帧 native 调用次数（应 == agent 数）。",
      "相同 seed 相同输入，验证输出与批量模式在容差内一致。",
      "在 UI 上明确标注 ANTI-PATTERN，防止未来的自己误用。",
      "提交对照记录。",
    ],
    debuggingNotes: [
      "两模式输出不一致：先确认共用同一份核心积分代码与同一 seed，再查 dt 累积顺序。",
      "浮点容差：用 epsilon 比较而不是完全相等，容差值写进记录。",
      "计数器归零时机放在帧首，别把初始化调用算进去。",
    ],
    publicShowcaseSeed: "『calls/frame = 5000』和『calls/frame = 1』两张 HUD 截图并排，是反模式叙事最直观的一图流。",
  },

  // ------------------------------------------------------------
  // M7 — 基准运行器 + HUD
  // ------------------------------------------------------------
  {
    id: "m7",
    code: "M7",
    title: "基准运行器 + HUD",
    regionId: "benchmark_plains",
    type: "main",
    order: 9,
    narrativeHook: "平原中央的大石碑终于立起：从此测量有了仪式，数字有了尊严。",
    objective: "实现固定 seed、warmup、测量帧窗口、median/p95、GC alloc、运行时 HUD 与 CSV/JSON 导出。",
    whyItMatters:
      "没有方法论的 benchmark 只是轶事。固定 seed、剔除 warmup、报告中位数与尾部延迟——这是把'我觉得更快'变成'数据显示'的全部分量。",
    prerequisites: ["m6"],
    definitionOfDone: [
      "基准运行器支持 1k / 5k / 10k agents。",
      "所有模式使用相同固定 seed。",
      "warmup 帧被排除。",
      "报告 median 与 p95。",
      "记录 GC allocation。",
      "运行时 HUD 显示：mode、agent count、native calls/frame、ms/frame、GC alloc、checksum。",
      "CSV 或 JSON 导出可用。",
    ],
    evidenceRequired: [
      { id: "commit", type: "commit_hash", label: "Commit Hash", placeholder: "例如 a1b2c3d" },
      { id: "hud_shot", type: "screenshot_note", label: "HUD 截图", placeholder: "截图路径" },
      {
        id: "export_sample",
        type: "benchmark_file",
        label: "导出的 CSV/JSON 样本",
        placeholder: "粘贴前几行或文件路径",
        multiline: true,
      },
      {
        id: "methodology",
        type: "doc_section",
        label: "基准方法论笔记",
        placeholder: "seed / warmup / 测量窗口 / 统计口径 / 渲染隔离",
        multiline: true,
      },
      {
        id: "linkedin_seed",
        type: "linkedin_draft",
        label: "LinkedIn 草稿种子",
        placeholder: "为这个 benchmark 写 3-5 句展示草稿",
        multiline: true,
      },
    ],
    skills: ["skill_benchmarking", "skill_gc_alloc", "skill_hud", "skill_profiling", "skill_bench_method", "skill_linkedin"],
    artifactIds: ["art_m7"],
    rewards: { xp: 220, gold: 120, skillPoints: 3, reputation: 15, insight: 0 },
    aiPrompt: forgePrompt(
      "M7",
      "基准运行器 + HUD",
      "构建 benchmark runner：固定 seed 初始化 1k/5k/10k agents；跳过 warmup 帧后测量 N 帧；对每模式统计 ms/frame 的 median 与 p95、GC alloc、native calls/frame、checksum；运行时 HUD 展示以上指标；支持导出 CSV 或 JSON。",
    ),
    resources: [
      { label: "Unity — Profiler", url: "https://docs.unity3d.com/Manual/Profiler.html" },
      { label: "Unity — ProfilerRecorder", url: "https://docs.unity3d.com/ScriptReference/Unity.Profiling.ProfilerRecorder.html" },
    ],
    commonTraps: [
      "只报告最好的一帧。",
      "把渲染成本混进仿真测量。",
      "对比输出不一致的模式。",
      "跑 native Debug 构建却假装是最终结果。",
    ],
    interviewExplanation: "我测量 interop，而不是猜测。",
    nextRisk: "在没有 Burst 基线之前，任何'native 更快'的结论都是提前庆祝。",
    unlocks: ["m8"],
    estimate: "120–180 分钟",
    conceptMap: [
      "固定 seed",
      "warmup 剔除",
      "测量帧窗口",
      "median / p95",
      "GC alloc 记录",
      "运行时 HUD",
      "CSV/JSON 导出",
    ],
    filesToCreate: [
      "BenchmarkRunner.cs（场景/模式/规模编排）",
      "FrameStats.cs（采样、median/p95 统计）",
      "GC alloc 采样（ProfilerRecorder）",
      "BenchmarkHud.cs（运行时面板）",
      "CSV/JSON 导出器",
      "docs/BENCHMARK_METHODOLOGY.md 正文",
    ],
    steps: [
      "定义基准配置：模式 × agent 规模（1k/5k/10k）× 帧窗口。",
      "所有模式共用同一个固定 seed 的初始化。",
      "跳过前 N 帧 warmup，再采样 M 帧。",
      "对 ms/frame 计算 median 与 p95（排序取分位，别用平均）。",
      "用 ProfilerRecorder 记录 GC alloc/frame。",
      "HUD 显示：mode、agent count、calls/frame、ms/frame、GC alloc、checksum。",
      "把每轮结果写出 CSV 或 JSON。",
      "把 seed/warmup/窗口/统计口径/渲染隔离写进 BENCHMARK_METHODOLOGY.md。",
      "提交导出样本与方法论文档。",
    ],
    debuggingNotes: [
      "数字抖动大：检查是否混入了渲染成本——把仿真计时单独用 Stopwatch 包住。",
      "GC alloc 恒为 0 却不敢信：故意插入一次分配验证采样器工作。",
      "vsync 会把 ms/frame 钳到刷新率：测量窗口内关掉或用仿真段计时。",
    ],
    publicShowcaseSeed: "HUD 截图 + CSV 前几行 + 方法论要点，凑成第一篇『我如何测量边界成本』的 LinkedIn/博客主体。",
  },

  // ------------------------------------------------------------
  // M8 — Burst 基线
  // ------------------------------------------------------------
  {
    id: "m8",
    code: "M8",
    title: "Burst 基线",
    regionId: "benchmark_plains",
    type: "main",
    order: 10,
    narrativeHook: "公平的审判需要最强的辩方证人：Unity 自己的高性能路径。",
    objective: "加入 C# Jobs + Burst 模式，形成公平对比。",
    whyItMatters:
      "跳过 Burst 直接吹捧 C++，会让整个研究失去可信度。承认并测量 Unity 的高性能路径，你的结论才有资格被引用。",
    prerequisites: ["m7"],
    definitionOfDone: [
      "Burst 模式存在。",
      "Burst 输出与其他模式校验一致。",
      "基准报告包含 Burst 模式。",
      "文档明确说明：这不是 C++ 崇拜。",
    ],
    evidenceRequired: [
      { id: "commit", type: "commit_hash", label: "Commit Hash", placeholder: "例如 a1b2c3d" },
      {
        id: "report",
        type: "benchmark_file",
        label: "含 Burst 的基准报告",
        placeholder: "粘贴报告关键行或文件路径",
        multiline: true,
      },
      {
        id: "fairness",
        type: "text_reflection",
        label: "公平性简短说明",
        placeholder: "为什么必须有 Burst 基线？",
        multiline: true,
      },
      {
        id: "readme_para",
        type: "doc_section",
        label: "更新后的 README 段落",
        placeholder: "粘贴'这不是 C++ 崇拜'的段落",
        multiline: true,
      },
    ],
    skills: ["skill_burst", "skill_thread"],
    artifactIds: ["art_m8"],
    rewards: { xp: 200, gold: 100, skillPoints: 2, reputation: 10, insight: 0 },
    aiPrompt: forgePrompt(
      "M8",
      "Burst 基线",
      "用 C# Job System + Burst 实现与 native 相同的 agent 步进逻辑；验证输出与其他模式一致（checksum）；把 Burst 模式纳入基准报告；在 README 明确写下'本项目不是 C++ 崇拜'的公平性声明。",
    ),
    resources: [
      { label: "Unity — Burst", url: "https://docs.unity3d.com/Packages/com.unity.burst@latest" },
      { label: "Unity — Job System", url: "https://docs.unity3d.com/Manual/JobSystem.html" },
    ],
    commonTraps: ["Burst 编译未生效（没看 Inspector 确认）。", "Jobs 并行度与 native 单线程不对等却直接对比。", "输出未校验就宣布结论。"],
    interviewExplanation: "我不宣称 C++ 自动更快；我拿它与 Unity 自己的高性能路径对比。",
    nextRisk: "四种模式齐备，Boss 之门在等你把方法论讲成一个 90 秒的故事。",
    unlocks: ["boss_benchmark"],
    estimate: "90–150 分钟",
    conceptMap: [
      "IJob / IJobFor",
      "[BurstCompile]",
      "NativeArray 数据通道",
      "输出 checksum 校验",
      "并行度对等说明",
      "公平性声明",
    ],
    filesToCreate: [
      "AgentStepJob.cs（Burst 编译的步进 Job）",
      "Burst 模式接入 BenchmarkRunner",
      "输出一致性校验记录",
      "README『这不是 C++ 崇拜』段落",
    ],
    steps: [
      "用 IJobFor + [BurstCompile] 实现与 native 相同的积分逻辑。",
      "数据放 NativeArray<Agent>，避免任何托管分配。",
      "在 Burst Inspector 确认编译生效（看到向量化汇编）。",
      "相同 seed 下校验输出与其他模式一致。",
      "把 Burst 模式纳入基准，重新导出报告。",
      "在 README 写下公平性声明：单线程对单线程，或明确标注并行度差异。",
      "提交报告与 README 段落。",
    ],
    debuggingNotes: [
      "Burst 悄悄回退到 Mono：检查 Job 里是否用了托管类型或异常路径。",
      "Burst 比 native 快不奇怪——先检查两侧优化级别与并行度是否对等，再下结论。",
      "结果差距过大时，先看数据搬运（复制 vs 原地）是否公平。",
    ],
    publicShowcaseSeed: "四模式对比表（managed / Burst / native per-call / native batched）本身就是整个实验室 thesis 的证据核心。",
  },

  // ------------------------------------------------------------
  // BOSS — 边界成本试炼
  // ------------------------------------------------------------
  {
    id: "boss_benchmark",
    code: "BOSS",
    title: "边界成本试炼",
    regionId: "benchmark_plains",
    type: "boss",
    order: 11,
    narrativeHook: "试炼官只问一个问题：你的数字，凭什么让人相信？",
    objective: "汇总 Benchmark Plains 的证据，完成公开展示的第一步。",
    whyItMatters:
      "这是 Act I 的公开 demo 切片（Agent Swarm Boundary Benchmark）成型的时刻。它将成为你的第一件可对外展示的边界工程证据。",
    prerequisites: ["m4", "m5", "m6", "m7", "m8"],
    definitionOfDone: [
      "M4–M8 全部完成。",
      "基准输出已导出。",
      "HUD 截图存在。",
      "写出 90 秒讲解：如何设计 benchmark 使其测量边界成本而不是渲染成本？",
      "起草第一篇 LinkedIn/GitHub 展示笔记。",
    ],
    evidenceRequired: [
      {
        id: "export_confirm",
        type: "benchmark_file",
        label: "基准导出（路径或关键数据）",
        placeholder: "四种模式在 5k agents 下的 median/p95",
        multiline: true,
      },
      { id: "hud_confirm", type: "screenshot_note", label: "HUD 截图路径", placeholder: "截图路径" },
      {
        id: "explain_90s",
        type: "text_reflection",
        label: "90 秒方法论讲解",
        placeholder: "我如何把边界成本与渲染成本分离……",
        multiline: true,
      },
      {
        id: "showcase_draft",
        type: "linkedin_draft",
        label: "首篇 LinkedIn/GitHub 展示草稿",
        placeholder: "完整草稿（可此后润色）",
        multiline: true,
      },
    ],
    skills: ["skill_resume_bullet"],
    artifactIds: ["art_boss_benchmark"],
    rewards: { xp: 400, gold: 200, skillPoints: 1, reputation: 40, insight: 2 },
    aiPrompt: forgePrompt(
      "BOSS",
      "边界成本试炼",
      "扮演严格的性能工程面试官，围绕我的 Agent Swarm Benchmark 追问：seed 固定了吗？warmup 怎么处理？为什么用 median/p95？渲染成本如何隔离？GC alloc 怎么测的？然后帮我把回答打磨成 90 秒版本，并润色我的第一篇 LinkedIn 展示草稿。",
    ),
    resources: [],
    commonTraps: ["把展示草稿写成流水账。聚焦一个反直觉结论：native 不一定更快。", "在草稿里夸大结论。"],
    interviewExplanation: "我设计了隔离渲染成本的基准方法论，并用 median/p95、GC alloc 与 checksum 支撑结论。",
    nextRisk: "主线在此收官。最大的风险是恋战：给项目加 CI 门禁、发布 README，然后封盘——下一站是应用物理与 MuJoCo，不是更多边界功能。",
    unlocks: [],
    estimate: "45–60 分钟",
    conceptMap: [
      "四模式基准导出",
      "方法论答辩",
      "90 秒讲解",
      "首篇公开草稿",
      "平原试炼之印",
      "Act I 主线收官",
    ],
    filesToCreate: [
      "不写新代码。",
      "基准导出确认（路径或关键数据）。",
      "90 秒方法论讲解文本。",
      "首篇 LinkedIn/GitHub 展示草稿。",
    ],
    steps: [
      "汇总四模式在 5k agents 下的 median/p95 数据。",
      "让 AI 扮演性能面试官，围绕 seed/warmup/分位数/渲染隔离/GC 测量追问你。",
      "把回答打磨成 90 秒版本写下来。",
      "起草第一篇公开展示（聚焦『native 不一定更快』这一个反直觉结论）。",
      "提交答辩，铸成平原试炼之印。",
    ],
    debuggingNotes: [
      "讲解超过 90 秒：砍掉工具细节，只保留方法论决策与数据结论。",
      "草稿写不动：从那张四模式对比表开始，让数据先说话。",
    ],
    publicShowcaseSeed: "这是 Act I 公开 demo 切片（Agent Swarm Boundary Benchmark）的发布时刻——第一条真正建议公开的 LinkedIn/GitHub 内容。",
  },

  // ============================================================
  // 生产经验营地（Act 0 支线）— 整理旧装备
  // 全部可选：把五年 Unity 生产直觉变成有名字的证据，永不阻塞主线。
  // ============================================================
  {
    id: "b1",
    code: "B1",
    title: "生产装备盘点",
    regionId: "production_basecamp",
    type: "reflection",
    order: 30,
    optional: true,
    narrativeHook: "帐篷里摊开你的旧行囊。五年的战利品，比你以为的多得多。",
    objective: "盘点过去 Unity 移动生产经验，整理成一张不含雇主机密的装备清单。",
    whyItMatters:
      "转型不是从零开始。把隐性经验变成显性清单，你会发现自己已经拥有大量『边界工程』的前置装备——同时它也是所有未来简历与面试叙事的原材料。",
    prerequisites: ["q_r0"],
    definitionOfDone: [
      "列出 8–15 条真实做过的事（项目类型、系统、工具、平台）。",
      "全部用可公开的语言描述，不含雇主专有细节。",
      "标注其中 3 条与 native/性能/运行时最相关的。",
    ],
    evidenceRequired: [
      {
        id: "inventory",
        type: "doc_section",
        label: "装备清单（8–15 条）",
        placeholder: "例如：接入过 N 家 SDK；处理过 Android/iOS 生命周期差异；做过内存优化专项……",
        multiline: true,
      },
      {
        id: "surprise",
        type: "text_reflection",
        label: "一条让你意外的发现",
        placeholder: "盘点时发现的、原来我早就会的东西",
        multiline: true,
      },
    ],
    skills: [],
    artifactIds: ["art_b1"],
    rewards: { xp: 50, gold: 30, skillPoints: 1, reputation: 0, insight: 1 },
    aiPrompt: forgePrompt(
      "B1",
      "生产装备盘点",
      "帮我盘点 5 年 Unity 移动生产经验：引导我按『项目类型 / 核心系统 / 工具链 / 平台问题 / 性能专项』五类回忆，整理成 8-15 条不含雇主机密的装备清单，并标出与 native 边界、运行时、性能最相关的 3 条。",
    ),
    resources: [],
    commonTraps: ["写成流水账简历。要的是能力清单，不是工作经历。", "夹带雇主专有细节。全部换成通用描述。"],
    interviewExplanation: "我系统盘点过自己的生产经验，清楚哪些旧能力直接迁移到运行时工程。",
    nextRisk: "盘点会带来『原来我很强』的良好感觉。别停在感觉——主线的证据还在等你。",
    unlocks: [],
    estimate: "30–45 分钟",
    steps: [
      "按五类回忆：项目类型 / 核心系统 / 工具链 / 平台问题 / 性能专项。",
      "每类写 2–4 条，全部用可公开语言。",
      "标注与 native/性能/运行时最相关的 3 条。",
      "写下一条让你意外的发现。",
    ],
    publicShowcaseSeed: "清单本身不公开，但它是未来 LinkedIn 自我介绍与简历技能区的原材料库。",
  },
  {
    id: "b2",
    code: "B2",
    title: "Unity 运行时心智模型",
    regionId: "production_basecamp",
    type: "training",
    order: 31,
    optional: true,
    narrativeHook: "你每天都在 Unity 的规则下干活。今天把规则本身画出来。",
    objective: "把 Unity 生命周期、主线程、managed runtime、GC、update loop、资产/运行时边界写成一页显性心智模型。",
    whyItMatters:
      "边界工程的前提是知道边界的哪一侧是什么。把『凭感觉知道』的 Unity 运行时规则显性化，M2-M3 的 P/Invoke 与生命周期设计会突然变得清晰。",
    prerequisites: ["q_r0"],
    definitionOfDone: [
      "一页心智模型：生命周期顺序、主线程规则、GC 触发、update loop。",
      "写出 3 条自己常年遵守但从没说出口的规则。",
      "明确资产加载与运行时逻辑的边界。",
    ],
    evidenceRequired: [
      {
        id: "model",
        type: "doc_section",
        label: "一页心智模型",
        placeholder: "Awake→OnEnable→Start→Update…；主线程规则；GC 何时触发；帧循环结构……",
        multiline: true,
      },
      {
        id: "rules",
        type: "text_reflection",
        label: "3 条隐性规则显性化",
        placeholder: "例如：Update 里绝不 new；协程不做重逻辑；……",
        multiline: true,
      },
    ],
    skills: ["skill_unity_runtime_model"],
    artifactIds: [],
    rewards: { xp: 60, gold: 30, skillPoints: 1, reputation: 0, insight: 0 },
    aiPrompt: forgePrompt(
      "B2",
      "Unity 运行时心智模型",
      "帮我把 Unity 运行时画成一页心智模型：脚本生命周期顺序、主线程规则、managed heap 与 GC、update loop 的帧结构、资产系统与运行时逻辑的边界。以我 5 年生产经验为基础，用检查提问的方式帮我暴露模糊区。",
    ),
    resources: [
      { label: "Unity — 脚本生命周期", url: "https://docs.unity3d.com/Manual/ExecutionOrder.html" },
    ],
    commonTraps: ["抄官方文档。要的是你脑中的模型，错了再修。", "写太细。一页装不下的部分说明还没消化。"],
    interviewExplanation: "我能清晰讲出 Unity 运行时的线程模型、GC 行为与帧循环结构。",
    nextRisk: "模型写完会想去『系统学习』。不要。回主线，让 M1-M3 检验这张图。",
    unlocks: [],
    estimate: "45–60 分钟",
    steps: [
      "先凭记忆写：生命周期顺序、主线程规则、GC、帧循环。",
      "对照文档修正一处以上错误（有错才说明在学习）。",
      "写出 3 条隐性规则。",
      "标注资产/运行时边界。",
    ],
    publicShowcaseSeed: "修正过的心智模型可以成为一篇『5 年 Unity 开发者重画运行时地图』的博客素材。",
  },
  {
    id: "b3",
    code: "B3",
    title: "移动生产摩擦提取",
    regionId: "production_basecamp",
    type: "reflection",
    order: 32,
    optional: true,
    narrativeHook: "那些让你加班的夜晚不是白熬的——它们是别人没有的地图。",
    objective: "提取移动生产中的真实摩擦主题：SDK 集成、平台构建、生命周期差异、内存/性能、工具链。",
    whyItMatters:
      "移动生产摩擦 × 仿真基础设施能力，是你未来最稀缺的组合卖点。生产交付的摩擦直觉——构建链、平台差异、真机验证——正是仿真行业面试里『能落地』的证据。",
    prerequisites: ["q_r0"],
    definitionOfDone: [
      "列出 5–8 个摩擦主题，每个附一个真实案例（可公开语言）。",
      "为 Top 3 摩擦写出当时的解法与现在会怎么改进。",
    ],
    evidenceRequired: [
      {
        id: "frictions",
        type: "doc_section",
        label: "摩擦主题清单（5–8 个）",
        placeholder: "SDK 集成地狱 / Android 构建链 / iOS 审核相关技术约束 / 低端机内存……",
        multiline: true,
      },
      {
        id: "top3",
        type: "text_reflection",
        label: "Top 3 摩擦：当时解法 + 现在的改进思路",
        placeholder: "每个 3-4 句",
        multiline: true,
      },
    ],
    skills: ["skill_mobile_production"],
    artifactIds: [],
    rewards: { xp: 50, gold: 30, skillPoints: 1, reputation: 0, insight: 1 },
    aiPrompt: forgePrompt(
      "B3",
      "移动生产摩擦提取",
      "帮我提取 Unity 移动生产的摩擦主题：用追问的方式引导我回忆 SDK 集成、平台构建、Android/iOS 生命周期、内存/性能、工具链五个领域的真实困难，整理成摩擦地图，并为 Top 3 写『当时解法 vs 现在改进』对照。",
    ),
    resources: [],
    commonTraps: ["只写抱怨不写解法。摩擦的价值在于你穿过了它。", "细节涉密。全部脱敏成通用工程问题。"],
    interviewExplanation: "我能系统讲述移动生产的真实约束，以及它们如何塑造我的工程判断。",
    nextRisk: "摩擦回忆容易变成情绪回放。提取完就收兵，别恋战。",
    unlocks: [],
    estimate: "30–45 分钟",
    publicShowcaseSeed: "摩擦地图是未来『Unity 移动生产幸存指南』系列博客的目录页。",
  },
  {
    id: "b4",
    code: "B4",
    title: "C# 热路径审计",
    regionId: "production_basecamp",
    type: "drill",
    order: 33,
    optional: true,
    narrativeHook: "你早就『凭手感』避开那些坑。今天给每个坑立一块碑。",
    objective: "把热路径直觉变成显性规则清单：allocations、LINQ、boxing、closures、struct 拷贝、GC。",
    whyItMatters:
      "M5-M8 的 benchmark 会拿 C# 路径与 native 路径对比。如果 C# 侧写得糟糕，对比就不公平。你的热路径直觉是保证对照实验可信的武器。",
    prerequisites: ["q_r0"],
    definitionOfDone: [
      "写出 6–10 条显性热路径规则，每条附『为什么』。",
      "给出至少一个 before/after 代码示例。",
      "标注哪些规则与 GC alloc 测量直接相关。",
    ],
    evidenceRequired: [
      {
        id: "rules",
        type: "doc_section",
        label: "热路径规则清单（6–10 条）",
        placeholder: "1. Update 内零分配，因为…… 2. 热路径禁 LINQ，因为…… 3. 值类型装箱发生在……",
        multiline: true,
      },
      {
        id: "example",
        type: "code_snippet",
        label: "一个 before/after 示例",
        placeholder: "贴一段『会分配』与『零分配』的对照代码",
        multiline: true,
      },
    ],
    skills: [],
    artifactIds: [],
    rewards: { xp: 60, gold: 30, skillPoints: 1, reputation: 0, insight: 0 },
    aiPrompt: forgePrompt(
      "B4",
      "C# 热路径审计",
      "帮我把 C# 热路径直觉显性化：围绕 allocations、LINQ、boxing、closures、struct 拷贝、GC 六个主题，用提问的方式帮我写出 6-10 条规则（每条带机制解释），并构造一个 before/after 零分配改写示例。",
    ),
    resources: [
      { label: "Unity — 性能优化 / GC", url: "https://docs.unity3d.com/Manual/performance-garbage-collector.html" },
    ],
    commonTraps: ["规则没有『为什么』。没有机制解释的规则是迷信。", "示例太复杂。一个函数就够。"],
    interviewExplanation: "我能解释每一条热路径规则背后的运行时机制，而不是背诵最佳实践。",
    nextRisk: "审计完会手痒想优化一切。热路径规则只在热路径生效——别把它带进原型代码。",
    unlocks: [],
    estimate: "45–60 分钟",
    publicShowcaseSeed: "规则清单可直接演化为一篇高质量博客：『五年 Unity 生产教我的 C# 热路径纪律』。",
  },
  {
    id: "b5",
    code: "B5",
    title: "玩法与仿真分离论",
    regionId: "production_basecamp",
    type: "reflection",
    order: 34,
    optional: true,
    narrativeHook: "帐篷的地图桌上有一条虚线：MonoBehaviour 的领地到此为止。",
    objective: "写清楚：为什么未来的确定性仿真核心不应该住在 MonoBehaviour 里。",
    whyItMatters:
      "这是 Act II 的思想地基。分不清『呈现层』与『仿真核心』的人，会把确定性内核写成另一个 Unity 场景脚本。现在想清楚，将来少走一年弯路。",
    prerequisites: ["q_r0"],
    definitionOfDone: [
      "写出 200–400 字的分离论证：帧率耦合、生命周期耦合、可测试性、确定性、平台耦合。",
      "画出（文本即可）理想的分层：仿真核心 / 边界 / 呈现层。",
    ],
    evidenceRequired: [
      {
        id: "argument",
        type: "doc_section",
        label: "分离论证（200–400 字）",
        placeholder: "确定性仿真核心不该住在 MonoBehaviour 里，因为……",
        multiline: true,
      },
      {
        id: "layers",
        type: "text_reflection",
        label: "分层示意（文本）",
        placeholder: "仿真核心（headless, 固定步长）→ 边界（C ABI）→ 呈现层（Unity）",
        multiline: true,
      },
    ],
    skills: ["skill_sim_split"],
    artifactIds: [],
    rewards: { xp: 60, gold: 30, skillPoints: 1, reputation: 0, insight: 1 },
    aiPrompt: forgePrompt(
      "B5",
      "玩法与仿真分离论",
      "和我辩论：为什么确定性仿真核心不应该住在 MonoBehaviour 里？请先让我陈述观点，然后从帧率耦合、生命周期耦合、可测试性、确定性、平台耦合五个角度追问我，最后帮我把论证收敛成 200-400 字。",
    ),
    resources: [],
    commonTraps: ["只喊口号（『解耦好』）不给机制。每条理由都要能落到具体代价。", "把 Unity 说得一无是处。Unity 是优秀的呈现层。"],
    interviewExplanation: "我能论证仿真核心与引擎呈现层分离的架构决策，以及它对确定性与可测试性的意义。",
    nextRisk: "想清楚了就够——不要现在就动手写内核。Act II 的门会在证据齐时打开。",
    unlocks: [],
    estimate: "30–45 分钟",
    publicShowcaseSeed: "这段论证将来会直接进入 Act II 内核项目的 README 第一章：Why headless。",
  },
  {
    id: "b6",
    code: "B6",
    title: "职业故事提取器",
    regionId: "production_basecamp",
    type: "reflection",
    order: 35,
    optional: true,
    narrativeHook: "营火边最后一项仪式：把经历讲成别人听得懂的故事。",
    objective: "把已有经验提炼成 2–3 个面试安全、不涉密的 STAR 故事。",
    whyItMatters:
      "面试的一半是叙事。提前把生产经历打磨成 STAR 结构（情境-任务-行动-结果），未来任何面试都能即取即用——而且它们与 Boundary Lab 的新证据会互相印证。",
    prerequisites: ["q_r0"],
    definitionOfDone: [
      "写出 2–3 个 STAR 故事，每个 6–10 句。",
      "全部可公开：无雇主机密、无夸大。",
      "至少一个故事与性能/稳定性/工具链相关。",
    ],
    evidenceRequired: [
      {
        id: "stories",
        type: "text_reflection",
        label: "2–3 个 STAR 故事",
        placeholder: "S：项目背景… T：我负责… A：我做了… R：结果是…",
        multiline: true,
      },
      {
        id: "bullet",
        type: "portfolio_note",
        label: "一条由故事提炼的简历要点",
        placeholder: "一行、有动词、有结果",
      },
    ],
    skills: ["skill_career_story"],
    artifactIds: ["art_b6"],
    rewards: { xp: 60, gold: 30, skillPoints: 1, reputation: 5, insight: 1 },
    aiPrompt: forgePrompt(
      "B6",
      "职业故事提取器",
      "帮我把 Unity 移动生产经历提炼成 2-3 个 STAR 面试故事：先用追问帮我找到有冲突有结果的经历，然后逐个打磨成 6-10 句的 STAR 结构，确保不涉密、不夸大，最后各提炼一条简历要点。",
    ),
    resources: [],
    commonTraps: ["故事没有 R（结果）。没有结果的故事只是经历。", "夸大个人贡献。团队工作说清楚自己的那一份。"],
    interviewExplanation: "我能用 STAR 结构讲述生产经历，且每个故事都有可验证的结果。",
    nextRisk: "旧故事整理完毕。新故事要靠主线任务铸造——回到 Bridge Village。",
    unlocks: [],
    estimate: "45–60 分钟",
    publicShowcaseSeed: "STAR 故事是 LinkedIn『关于我』板块与面试自我介绍的直接素材。",
  },
];

export const QUEST_BY_ID: Record<string, Quest> = Object.fromEntries(QUESTS.map((q) => [q.id, q]));

export const ORDERED_QUESTS: Quest[] = QUESTS.slice().sort((a, b) => a.order - b.order);
